### ISSUE TITLE
Expose AST of classes and functions via reflection

### ISSUE THREAD

**Issue by TimeToogo** [nikic/php-ast#1]
A benefit of an API such of this would be for analyzing code of user defined functions and classes at run time. Being able to get the AST of specific closures/functions/methods or classes/traits/interfaces would be very useful rather than having to parse an entire file as a string and attempting to locate the desired node.

Perhaps respective methods such as:

``` php
ReflectionFunctionAbstract::getAST()
ReflectionClass::getAST()
```

That would act equivalent to `ast\parseCode($code)` with the code to which the reflection is referring.

**Comment by nikic** [comment]
Here's the ticket for more accurate position information: https://bugs.php.net/bug.php?id=70024 Even if we don't add it to the AST, we can at least add the info to reflection.

**Comment by nikic** [comment]
Closing this, as it's out of scope for this extension and would require upstream changes in any case.
