### ISSUE TITLE
Deprecate parse_code $filename argument

### ISSUE THREAD

**Issue by nikic** [nikic/php-ast#104]
`ast\parse_code()` currently accepts a `$filename` argument. This argument is only used as the file name in error messages.

Are there any objections to deprecating this argument and dropping it in the future? It causes an unfortunate asymmetry between `parse_file()` and `parse_code()` and will make for ugly signatures if something like #87 is implemented.

cc @TysonAndre

**Comment by TysonAndre** [comment]
I'm using the $filename argument right now, in code that expects AST version 50.

1. It's useful when you're implementing a language server for the Language Server Protocol. You want ParseError->getMessage() to have the correct file name and the file contents that haven't been saved to disk yet.
2. It's useful if you've already loaded the file contents into a cache for other reasons (and code expects ParseError)

See https://github.com/phan/phan/blob/1.0.6/src/Phan/AST/Parser.php#L42-L63

This would require changing APIs to use a different exception hierarchy, and is inconvenient (for existing code expecting ParseError to be thrown) but doable.

- ParseError is a subclass of Error, and I don't see an obvious way to override or set `final public string getFile ( void )` in https://secure.php.net/manual/en/class.error.php

**Comment by TysonAndre** [comment]
Also see https://github.com/phan/phan/issues/1134 - Phan exits if any notices are seen when it is running

**Comment by nikic** [comment]
That's a very good point, I forgot that PHP provides no way of overriding the file name of an exception. In that case we should definitely keep the functionality.

Thanks for the feedback!
