### ISSUE TITLE
Publish a 1.0.1 release

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#113]
Reasons:

- Fixes PHP 7.4-dev/master crash and incompatibilities for now, which is convenient for people testing unstable php versions
- `new \ast\Node()` also crashes due to calling ast_update_property
- Makes it easier to start testing against the experimental AST version 70 (earlier) in preparation for PHP 7.4 betas

I've already updated package.xml's changelog and file list, apart from the date, version, and needing to duplicate the most recent entries

**Comment by nikic** [comment]
I applied another master fix and released v1.0.1.
