### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php-7.0.10-ts\ext\php_ast.dll' - %1 is not a valid Win32 application.  in Unknown on line 0

### ISSUE THREAD

**Issue by sujit-birje04** [nikic/php-ast#116]
Hi,

I've followed the instructions:

1. I am running PHP 7.0.10 on Windows 10.
2. I downloaded the files from [here](https://windows.php.net/downloads/pecl/releases/ast/0.1.6/php_ast-0.1.6-7.0-nts-vc14-x64.zip). 
 - Also tried 32 bit version
3. I placed the `php_ast.dll` into the respective `ext` folder.
4. I added `extension=php_ast.dll` to my `php.ini`

Now when I run `php -v`, I get the following output:
_PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php-7.0.10-ts\ext\php_ast.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0_

_Warning: PHP Startup: Unable to load dynamic library 'C:\php-7.0.10-ts\ext\php_ast.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0_

**Comment by nikic** [comment]
You seem to be using a TS PHP build and loading the NTS ast DLL. If you are using a TS PHP build, you also need to use the TS DLL.

**Comment by sujit-birje04** [comment]
@nikic thank you for quick reply, I will try search for TS DLL.

Please update if you have link for the same.

**Comment by nikic** [comment]
@sujit-birje04 The TS DLLs are in the same directory: https://windows.php.net/downloads/pecl/releases/ast/0.1.6/

**Comment by sujit-birje04** [comment]
@nikic You are great, Thank you.

Going to explore more now, Thanks a lot for such quick support.

**Comment by sujit-birje04** [comment]
Working for me now, Closing the issue. 

Thank you @nikic
