### ISSUE TITLE
Change AST version 70 from experimental to current?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#118]
e.g. as a 1.0.2 release

The experimental status of version 70 discourages switching Phan/other uses of php-ast to AST version 70.

Anything else that changes in php 7.4-dev can go into version 80.

Version 70 is the only way to access data types of property groups - users may take months to upgrade php-ast so this is being requested earlier.

**Comment by nikic** [comment]
I think updating the readme to drop the experimental bit should be enough (it makes no difference from the implementation perspective).
