### ISSUE TITLE
Provide a node ID in the AST

### ISSUE THREAD

**Issue by tgalopin** [nikic/php-ast#136]
Hello!

I currently encounter the following problem:

1. During my visiting of files, I collect symbols by analyzing the AST. For each symbol created this way, I need to keep somewhere the information that this symbol was created by a specific node ;
2. Storing the node itself is memory inefficient as it keeps a reference to the AST in many places ;
3. I would like to keep only a reference to this node, but this reference should stay the same if I call the parse_file method multiple times so that I can safely reference the node ;

The best way I can think of to achieve this is by creating an incremented node ID. If each node in the AST of a file is given a number by counting the position of the node in the file, this position won't change if the file don't change, making it useful to reference a node in a file.

I can definitely do this in PHP, but there are two issues: the Node class don't have an ID property which makes `$node->id` a dynamic declaration and it's probably much slower than a C implementation would be.

Thus this question: could it be possible to add such feature :) ?

**Comment by tgalopin** [comment]
@TysonAndre thank for your reply! How do you compute a stable hash of nodes in Phan?

**Comment by TysonAndre** [comment]
https://github.com/phan/phan/blob/master/src/Phan/AST/ASTHasher.php#L16-L68

That's for the contents of the node, and it has some limitations, e.g. the `ast\Node` for `__LINE__` or `__METHOD__` is treated the same no matter what the actual line or method is.
