### ISSUE TITLE
Publish a 1.0.5 release

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#142]
http://pecl.php.net/package/ast has me as a developer instead of a lead again. I'm not sure if it's due to the `<developer>` tag in package.xml for the 1.0.4 release, or for another reason. ( https://github.com/nikic/php-ast/pull/139#issuecomment-552248032 )

> Nikita Popov (lead) [details]
> Tyson Andre (developer) [details]

cc @nikic

**Comment by remicollet** [comment]
> I'm not sure if it's due to the <developer> tag in package.xml

Yes, during upload (of 1.0.4) lead / dev roles are updated with package.xml values

**Comment by nikic** [comment]
Role should be restored now.

**Comment by remicollet** [comment]
@TysonAndre any reason to not publish 1.0.5 on pecl ?
Everything seems ok now, current ACL and package.xml
