### ISSUE TITLE
Is the latest version compatible with PHP7.4?

### ISSUE THREAD

**Issue by jansor** [nikic/php-ast#144]
Hi, 
I check the PECL for windows build of AST. When i look under the download section for the latest version of AST 1.0.5 i see only support until PHP version 7.3

When i try to use 1.0.5 under PHP7.4 i get the following error Message when i first load the site:
PHP Startup: Unable to load dynamic library 'ast' (tried: D:\Inetpub\PHP7.4\ext\ast (The specified module could not be found.), D:\Inetpub\PHP7.4\ext\php_ast.dll (The specified procedure could not be found.)

Can you confirm if version 1.0.5 should be working with PHP7.4?

Otherwise i need to check my settings again.

Thanks

**Comment by nikic** [comment]
The extension is compatible with 7.4, but windows DLL builds have not been triggered for 7.4 yet (for all extensions). @cmb69 Any idea when that will happen?

**Comment by cmb69** [comment]
The mass rebuild will likely happen next week, but snapshot builds for PECL/ast 1.0.5 (and for some other extensions which have had new releases recently) are [already available](https://windows.php.net/downloads/pecl/snaps/ast/1.0.5/).

**Comment by jansor** [comment]
Ok great to hear, i need to learn to wait patiently ;) , Thank you for effort and support

**Comment by TysonAndre** [comment]
These are out on http://pecl.php.net/package/ast/1.0.5/windows
