### ISSUE TITLE
Supporting TYPE_MIXED from php 8.0 mixed type

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#154]
My thoughts:

It seems like `mixed` isn't a reserved keyword, so the approach used for `iterable`(7.1) and `object`(7.2) would be consistent with prior releases, and existing tooling would point out that there was no class with name `mixed` (if there wasn't).

In AST version 70 and below, continue returning a `ast\AST_NAME`(NAME_NOT_FQ) with the name "mixed" (preserve original case if available)

1. Make PHP 8.0 emulate php 7.x
2. Create a brand new AST version 75 where php 7 and 8 will return AST_TYPE with TYPE_MIXED

https://github.com/TysonAndre/php-ast/compare/is_mixed?targetBranch=master is a WIP branch for this that doesn't yet introduce a new version

**Comment by GrahamCampbell** [comment]
It would be good to able to parse php 7 separately to php 8, like php 5. This would mean php 7 parsing not handling union types anymore.

**Comment by TysonAndre** [comment]
> like php 5

The earliest release of php that `php-ast` supported is php 7.0, when PHP started having an actual AST.

> It would be good to able to parse php 7 separately to php 8, like php 5. This would also mean php 7 parsing not handling union types anymore.

https://github.com/nikic/php-ast#ast-versioning describes the policy the maintainers are following

> The ast\parse_code() and ast\parse_file() functions each accept a required AST $version argument. The idea behind the AST version is that we may need to change the format of the AST to account for new features in newer PHP versions, or to improve it in other ways. **Such changes will always be made under a new AST version, while previous formats continue to be supported for some time.**

PHP 7.4 support will be dropped eventually, but not soon. probably around the end of active or security support for php 7.4. https://www.php.net/supported-versions.php

**Comment by GrahamCampbell** [comment]
Ah yes, sorry. I was getting mixed up with the php parser package (implemented in PHP).

**Comment by TysonAndre** [comment]
> Ah yes, sorry. I was getting mixed up with the php parser package (implemented in pure PHP).

Understandable, I wondered if you were thinking of that instead - I don't do any work on php-parser, so I don't have any thoughts there.
