### ISSUE TITLE
Idea: Adding new parameter flag PARAM_MODIFIER_PUBLIC for AST_PARAM

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#167]
- In PHP 7.x, these would be new bit flags guaranteed to be different from PARAM_REF and PARAM_VARIADIC in 7.0-7.4. Currently, there's some overlap, which I previously dealt with by limiting when the metadata was published
- In PHP 8.0, PARAM_MODIFIER_PUBLIC would be equal to MODIFIER_PUBLIC and redundant (same for protected/private)

```c
static const char *param_flags[] = {
	AST_FLAG(PARAM_REF),
	AST_FLAG(PARAM_VARIADIC),
#if PHP_VERSION_ID >= 80000
	AST_FLAG(MODIFIER_PUBLIC),
	AST_FLAG(MODIFIER_PROTECTED),
	AST_FLAG(MODIFIER_PRIVATE),
#endif
	NULL
};
```

Of course, it's doable to polyfill this in pure PHP in applications that support it, but I think that having the same documented flag names in php 7 and 8 for ast\get_metadata() would be more consistent and easier to polyfill.
I can implement this if there's interest.

**Comment by nikic** [comment]
Sounds reasonable to me.
