### ISSUE TITLE
Changing values of constants

### ISSUE THREAD

**Issue by unkind** [nikic/php-ast#170]
I see that values of constants in `ast_stub.php` keep changing, e.g. `ast\flags\MAGIC_DIR` was 372, now it's 377.

Why it happens and why you don't expose stubs via extension itself, so I can refer them via extesion-provided constants at least?

**Comment by unkind** [comment]
Ah, constants exist with installed extension, but the issue with stubs is still relevant.

**Comment by nikic** [comment]
The stub files use the constant values from current master and may be different on older PHP version. The actual values are irrelevant though, only the names matter.

**Comment by TysonAndre** [comment]
Additionally, you don't load use ast_stub.php when the PECL php-ast extension is loaded.

The stub files are provided for:
1. Documentation readable in a simple web browser or text editor, like many PECL ast extensions provide
2. IDE stubs similar to https://github.com/JetBrains/phpstorm-stubs for people developing for applications that have php-ast (when they don't have php-ast installed)
3. A starting point for anyone creating their own stubs or a polyfill, such as the ones mentioned in the README

**Comment by unkind** [comment]
On other hand, it makes impossible to serialize AST effectively. Today this node is 42, tomorrow it's they very different node, so I have to use string values for that? Otherwise it could be possible to serialize it like flatbuffers.
