### ISSUE TITLE
Dropping support for php 7.1 and older?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#180]
@nikic - What are your thoughts on dropping support for php 7.1 and older after releasing 1.0.10 - this would simplify the implementation a bit (stubs, ast coercion logic on PHP_VERSION_ID, etc) and reduce the amount of testing

**Comment by nikic** [comment]
Yeah, I think it's fine to drop support for PHP <= 7.1.

**Comment by TysonAndre** [comment]
This was done in #185 , along with deprecating ast versions 50 and 60
