### ISSUE TITLE
Add ast_dump option: AST_DUMP_EXCLUDE_DOC

### ISSUE THREAD

**Issue by fan-y-mishiba2** [nikic/php-ast#191]
Hi,

I want to exclude the docComment from the output of the utils.php\ast_dump().
How about adding an option?

---

phpDocの修正がAST解析結果に出力されてしまうとBefore/Afterの比較がしづらいので除外したいと考えています。
ast_dump() のオプションに追加するのはいかがでしょうか？

**Comment by nikic** [comment]
I'm okay with having the option.

**Comment by fan-y-mishiba2** [comment]
Why? https://travis-ci.org/github/nikic/php-ast/jobs/737722549
--


The following is the result I checked.

<details><summary>$ docker run --rm -it  php:8.0.0RC2-cli bash</summary></details>
<details>
<summary>root@bfec2bb44b2a:~# git clone --depth=50 https://github.com/nikic/php-ast.git nikic/php-ast</summary>

Cloning into 'nikic/php-ast'...
remote: Enumerating objects: 416, done.
remote: Counting objects: 100% (416/416), done.
remote: Compressing objects: 100% (213/213), done.
remote: Total 416 (delta 283), reused 294 (delta 200), pack-reused 0
Receiving objects: 100% (416/416), 128.99 KiB | 367.00 KiB/s, done.
Resolving deltas: 100% (283/283), done.

</details>
<details><summary>root@bfec2bb44b2a:~# cd nikic/php-ast</summary></details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# git fetch origin +refs/pull/192/merge:</summary>

remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 4), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/nikic/php-ast
 * branch            refs/pull/192/merge -> FETCH_HEAD

</details>
<details><summary>root@bfec2bb44b2a:~/nikic/php-ast# git checkout -qf FETCH_HEAD</summary></details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# phpize</summary>

Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
root@bfec2bb44b2a:~/nikic/php-ast# ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20200930
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable ast support... yes, shared
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h

</details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# make</summary>

/bin/bash /root/nikic/php-ast/libtool --mode=compile cc -I. -I/root/nikic/php-ast -I/root/nikic/php-ast/include -I/root/nikic/php-ast/main -I/root/nikic/php-ast -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -c /root/nikic/php-ast/ast.c -o ast.lo
mkdir .libs
 cc -I. -I/root/nikic/php-ast -I/root/nikic/php-ast/include -I/root/nikic/php-ast/main -I/root/nikic/php-ast -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/nikic/php-ast/ast.c  -fPIC -DPIC -o .libs/ast.o
/bin/bash /root/nikic/php-ast/libtool --mode=compile cc -I. -I/root/nikic/php-ast -I/root/nikic/php-ast/include -I/root/nikic/php-ast/main -I/root/nikic/php-ast -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -c /root/nikic/php-ast/ast_data.c -o ast_data.lo
 cc -I. -I/root/nikic/php-ast -I/root/nikic/php-ast/include -I/root/nikic/php-ast/main -I/root/nikic/php-ast -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/nikic/php-ast/ast_data.c  -fPIC -DPIC -o .libs/ast_data.o
/bin/bash /root/nikic/php-ast/libtool --mode=link cc -shared -I/root/nikic/php-ast/include -I/root/nikic/php-ast/main -I/root/nikic/php-ast -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -o ast.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/nikic/php-ast/modules  ast.lo ast_data.lo
cc -shared  .libs/ast.o .libs/ast_data.o   -Wl,-soname -Wl,ast.so -o .libs/ast.so
creating ast.la
(cd .libs && rm -f ast.la && ln -s ../ast.la ast.la)
/bin/bash /root/nikic/php-ast/libtool --mode=install cp ./ast.la /root/nikic/php-ast/modules
cp ./.libs/ast.so /root/nikic/php-ast/modules/ast.so
cp ./.libs/ast.lai /root/nikic/php-ast/modules/ast.la
PATH="$PATH:/sbin" ldconfig -n /root/nikic/php-ast/modules
=---------------------------------------------------------------------
Libraries have been installed in:
   /root/nikic/php-ast/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
=---------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

</details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# make install</summary>

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20200930/

</details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# php --ini</summary>

Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini

</details>
<details><summary>root@bfec2bb44b2a:~/nikic/php-ast# echo "extension=ast.so" >> /usr/local/etc/php/php.ini</summary></details>
<details>
<summary>root@bfec2bb44b2a:~/nikic/php-ast# REPORT_EXIT_STATUS=1 php ./run-tests.php -P -q --show-diff</summary>

=====================================================================
PHP         : /usr/local/bin/php
PHP_SAPI    : cli
PHP_VERSION : 8.0.0RC2
ZEND_VERSION: 4.0.0-dev
PHP_OS      : Linux - Linux bfec2bb44b2a 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64
INI actual  : /usr/local/etc/php/php.ini
More .INIs  : /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
CWD         : /root/nikic/php-ast
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2020-10-22 09:20:18
=====================================================================
PASS ast_dump() test [tests/001.phpt]
PASS Array destructuring [tests/array_destructuring.phpt]
PASS Array destructuring (using unkeyed list()) [tests/array_destructuring_old.phpt]
PASS Assign op flags [tests/assign_ops.phpt]
PASS ast_dump() with AST_DUMP_EXCLUDE_DOC [tests/ast_dump_with_exclude_doc.phpt]
PASS ast_dump() with AST_DUMP_LINENOS [tests/ast_dump_with_linenos.phpt]
PASS Attributes in PHP 8.0 on globals [tests/attributes_01.phpt]
PASS Attributes in PHP 8.0 on classes [tests/attributes_02.phpt]
PASS AST_GREATER(_EQUAL) converted to AST_BINARY_OP [tests/binary_ops.phpt]
PASS By-reference array destructuring (PHP 7.3) [tests/by_ref_destructuring.phpt]
PASS Test parse and dump of class [tests/class.phpt]
PASS Class constants [tests/class_consts.phpt]
PASS Class constants in AST version 80 [tests/class_consts_80.phpt]
PASS Class properties in AST version 50 [tests/class_name_version_50.phpt]
PASS Class properties in AST version 70 [tests/class_name_version_70.phpt]
PASS $x::class in PHP 8.0 [tests/class_on_objects.phpt]
PASS Different class types [tests/class_types.phpt]
PASS Closure uses should parse to CLOSURE_USE_VAR nodes [tests/closure_use_vars.phpt]
PASS Null-coalesce operator [tests/coalesce.phpt]
PASS AST_CONCAT with/without parenthesis [tests/concat.phpt]
PASS ast\Node has a __construct method [tests/constructor.phpt]
PASS Closures should have unique identifiers within parsed code in version 50 [tests/decl_ids.phpt]
PASS As of version 50 Decl is no more [tests/decl_normalization.phpt]
PASS ast\parse_file() with empty file [tests/empty_file_parse.phpt]
PASS eval() and include parsing [tests/eval_include.phpt]
PASS Uses only make sense on closures [tests/functions_dont_use.phpt]
PASS Flag on generator functions in PHP 7.1 [tests/generator_flag.phpt]
PASS Test ast\get_kind_name() [tests/get_kind_name.phpt]
PASS ast\get_supported_versions() function [tests/get_supported_versions.phpt]
PASS Magic constants [tests/magic_constants.phpt]
PASS Match expression in PHP 8.0 [tests/match_expression.phpt]
PASS AST metadata [tests/metadata.phpt]
PASS Mixed types in PHP 8.0 [tests/mixed_type.phpt]
PASS Multi catch [tests/multi_catch.phpt]
PASS Multiple final multipliers should generate CompileError, not a fatal error [tests/multiple_final_modifiers.phpt]
PASS Name nodes [tests/name_node.phpt]
PASS Named child nodes [tests/named_children.phpt]
PASS Nested statement lists [tests/nested_stmt_lists.phpt]
PASS new ast\Node() throwing [tests/node_constructor_throw.phpt]
PASS Nop statements [tests/nop_statements.phpt]
PASS Nullable types [tests/nullable_types.phpt]
PASS The object type is recognized [tests/object_type.phpt]
PASS Function parameters [tests/params.phpt]
PASS ast\parse_code() throwing a ParseError [tests/parse_code_parse_error.phpt]
PASS ast\parse_file() on valid file [tests/parse_file.phpt]
PASS ast\parse_file() on file that does not exist [tests/parse_file_not_existing.phpt]
PASS ast\parse_file() on file with parse error [tests/parse_file_parse_error.phpt]
PASS '??=' operator in PHP 7.4 [tests/php74_ast_assign_coalesce.phpt]
PASS '$x{"offset"}' flag in PHP 7.4 [tests/php74_dim_alternative_syntax.phpt]
PASS Class properties in AST version 70 (php 7.0+) [tests/php74_ordinary_class.phpt]
PASS parenthesized conditionals in PHP 7.4 [tests/php74_parenthesized_conditional.phpt]
PASS Property type hints in PHP 7.4 [tests/php74_type_hints.phpt]
PASS Named parameters in PHP 8.0 [tests/php80_named_params.phpt]
PASS Non-capturing catches in PHP 8.0 [tests/php80_noncapturing_catch.phpt]
PASS Nullsafe operator in PHP 8.0 [tests/php80_nullsafe_operator.phpt]
PASS Constructor property promotion in PHP 8.0 [tests/php80_promotion.phpt]
PASS Union types in PHP 8.0 [tests/php80_static_type.phpt]
PASS Union types in PHP 8.0 [tests/php80_union_types.phpt]
PASS Union types in PHP 8.0 [tests/php80_union_types_false.phpt]
PASS Union types in PHP 8.0 (nullable) [tests/php80_union_types_nullable.phpt]
PASS Doc comments on properties [tests/prop_doc_comments.phpt]
PASS Arrow functions ('fn($x) => $x') in PHP 7.4 [tests/short_arrow_function.phpt]
PASS Arrow functions and types ('fn($x) => $x') in PHP 7.4 [tests/short_arrow_function_return.phpt]
PASS Statement list normalization [tests/stmt_list.phpt]
PASS try / catch / finally [tests/try_catch_finally.phpt]
PASS Type hints [tests/type_hints.phpt]
PASS Convert unary ops AST_(SILENCE|UNARY_(PLUS|MINUS)) to flags of ZEND_AST_UNARY_OP [tests/unary_ops.phpt]
PASS Test parse and dump of use declarations [tests/use_declarations.phpt]
PASS Version errors [tests/version_errors.phpt]
PASS zpp failures throw TypeError [tests/zpp_errors.phpt]
=====================================================================
TIME END 2020-10-22 09:20:20

=====================================================================
TEST RESULT SUMMARY
=--------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   34
=--------------------------------------------------------------------

Number of tests :   70                70
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :   70 (100.0%) (100.0%)
=--------------------------------------------------------------------
Time taken      :    2 seconds
=====================================================================

</details>
