### ISSUE TITLE
Utilize in C#?

### ISSUE THREAD

**Issue by ajhalls** [nikic/php-ast#194]
Is it possible to utilize this to parse PHP from within a C# application? Trying to think through how to do a basic test, this is what I have so far but I am not sure how to use the `ast` prefix for `ast\parse_code`.

```
  [DllImport(@"C:\PHPFunctions\bin\Debug\php_ast.dll")]
        public static extern long parse_code(string incoming);

        public string callLibFunction(string incoming)
        {            
            Console.WriteLine(parse_code(incoming).ToString()l);   
        }
```

**Comment by TysonAndre** [comment]
I'm not a C# programmer and this is out of the scope of the project.

https://github.com/peachpiecompiler/peachpie may or may not work with https://github.com/TysonAndre/tolerant-php-parser-to-php-ast as a substitute for php-ast, depending on what you're trying to do. I haven't figured out what peachpie's feature set is and haven't used it before. Compatibility with peachpie is not a goal of that project

php_ast.dll depends on php.exe's libraries for the tokenization code, some C constants, memory management, etc., so just importing php_ast.dll wouldn't be enough.

In theory, you could combine code from php-src and php-ast, combine it through php's embed sapi (which is obscure and unfamiliar even to me), and return the ast representation, e.g. converting it to json to be decoded with C#, and then working with that json representation, e.g. https://github.com/phan/demo/blob/9c1f3be82d1ff4cca68b33dac2170073fadaa3fa/pib_eval.c#L101-L125

https://hacks.mozilla.org/2019/12/using-webassembly-from-dotnet-with-wasmtime/ WebAssembly may or may not be useful; I don't do much work with it outside of browsers
