### ISSUE TITLE
Idea: Make ast\Node->endLineno a declared property?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#214]
Historically, `ast\Node\Decl` was a subclass of `ast\Node`, but in the latest AST parsing versions, everything is combined.

Alternately, php-ast could add an `attributes` array property to which a field `endLineno` could be added in AST versions exceeding some minimum value (and stop setting endLineno in older AST versions)

**Comment by nikic** [comment]
Hm, maybe we can make it part of children for the few nodes that need it?

**Comment by TysonAndre** [comment]
That's probably simpler and more memory efficient. I guess target the next AST "major" version (current =90, next $version=100?)

**Comment by nikic** [comment]
Yeah, exactly.

**Comment by nikic** [comment]
With `#[AllowDynamicProperties]`, I guess we can just leave this as-is?

**Comment by TysonAndre** [comment]
> With `#[AllowDynamicProperties]`, I guess we can just leave this as-is?

I agree
