### ISSUE TITLE
Windows: Pecl DLL for PHP 8.1 

### ISSUE THREAD

**Issue by jansor** [nikic/php-ast#215]
Hi 

Not sure if this is the correct place to check , tried to run PHP Phan today on php 8.1 but issue with AST under 8.1 could not be loaded.

I saw 1.0.14 already support parts of 8.1 but i cannot see the download for PHP 8.1 under PECL for windows. 

Anyhow, thanks for effort and development!!

**Comment by TysonAndre** [comment]
They'll be out a few weeks after php 8.1 is released. This applies to all PECLs. https://github.com/igbinary/igbinary/blob/master/WINDOWS.md is a different PECL, but has instructions and links for building PECL DLLs manually if you need them sooner. 

`phan --allow-polyfill-parser` exists but isn't precise, and is slower

https://externals.io/message/114751#116350

> Sorry for any potential confusion! There are currently no plans to
> change anything (some things might change in the long run, but that
> would be announced). The fact that no snapshot builds of PECL
> extensions for 8.1 have been yet done, is my fault. I forgot to update
> the build script to do so; I've just caught up on that, so that new PECL
> releases are supposed to build snapshots which would not be shown on
> pecl.php.net, but could be downloaded from
> https://windows.php.net/downloads/pecl/snaps/.
> 
> A full mass rebuild for all PECL packages is planned a few weeks after
> PHP 8.1.0 has been released. If anybody needs a snapshot build for a
> specific PECL package release right now, please ping me and I can
> trigger that build.

**Comment by TysonAndre** [comment]
e.g. it seems as if for some new extensions, PECL packages published after that date would have DLLs for new releases published to the snaps folder (e.g. https://windows.php.net/downloads/pecl/snaps/imagick/3.6.0/) but not linked from the pecl page(https://pecl.php.net/package/imagick/3.6.0/windows). There's no snaps for php-ast at the moment.

I expect them to be built and show up in the PECL page in a few weeks.

**Comment by nikic** [comment]
Not sure whether AppVeyor here is set up to produce artifacts. If it is, we could add 8.1 to the matrix and get them that way.

**Comment by TysonAndre** [comment]
> Not sure whether AppVeyor here is set up to produce artifacts. If it is, we could add 8.1 to the matrix and get them that way.

Appveyor only stores artifacts for a month - https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy . GitHub actions would work for longer persistence, but it doesn't seem worth it if the windows team would publish them soon.

**Comment by jansor** [comment]
Ow, ic, thanks for the update and information, i am updating my cli for now to use the polyfill, thanks again for the great work.

**Comment by nikic** [comment]
It looks like AppVeyor does produce artifacts, so you can pick the correct version from https://ci.appveyor.com/project/nikic/php-ast/builds/41686784 and go to the Artifacts tab.

**Comment by nikic** [comment]
Closing this, as you can either grab the artifacts from AppVeyor, or wait for the PECL rebuild for PHP 8.1.

**Comment by TysonAndre** [comment]
Snapshots are also available for https://windows.php.net/downloads/pecl/snaps/ast/1.0.16/
