### ISSUE TITLE
Why some built-in  functions have special AST type ?

### ISSUE THREAD

**Issue by ninthDevilHAUNSTER** [nikic/php-ast#222]
Hello, I am new to php-ast and I have a question in the process of using it.
Why do built-in functions like empty(), isset() etc. have a special ast type (like AST_EMTPY and AST_ISSET) while built-in functions like interval(), str_repalce() etc. have an ast type of AST_FUNCTION?

**Comment by nikic** [comment]
empty() and isset() are not functions, they are language construct that use function-like syntax. They do not behave like ordinary functions, e.g. `isset($undefVar)` would throw a warning if `isset()` were a normal function.
