### ISSUE TITLE
php-ast 1.1.0 DLL for Windows

### ISSUE THREAD

**Issue by Hackwar** [nikic/php-ast#236]
Hello and thank you for your work. When can we expect a precompiled DLL for windows for php-ast 1.1.0? Do you need help here somewhere?

**Comment by wo80** [comment]
It should be possible to build this using [cmb69/setup-php-sdk](https://github.com/cmb69/setup-php-sdk).

I tried setting up a workflow at https://github.com/wo80/php-ast-windows-build/blob/main/.github/workflows/ci.yml, but it seems to fail during the configure step. Got no time and interest to investigate further, but maybe someone here wants to fiddle around with it...

**Comment by wo80** [comment]
The build script is working now. `php_ast.dll` loads fine, `php -i` outputs
```
ast

ast support => enabled
extension version => 1.1.1-dev
AST version => Current version is 90. All versions (including experimental): {50, 60, 70, 80, 85, 90}
```
No further tests done.

@nikic Feel free to copy the workflow to your `main.yml`

**Comment by OwnerOfThisIsle** [comment]
The readme.md says to get it from https://windows.php.net/downloads/pecl/releases/ast/ , but there is no current version.
Who can do something about it?

**Comment by wo80** [comment]
@OwnerOfThisIsle If it's ok for you to use the build artifact, go to https://github.com/wo80/php-ast-windows-build, Actions tab, open latest commit "Update build file (8)" and scroll down to artifacts. You will find the "php_ast-8.2-x64-nts" archive there.

Direct download: [php_ast-8.2-x64-nts.zip](https://github.com/wo80/php-ast-windows-build/suites/11912968594/artifacts/623782755)

There's also a fork providing artifacts for other PHP versions: https://github.com/theresnotime/php-ast-windows-build/actions/runs/4610199296

**Comment by neuberkauf** [comment]
@wo80 Thanks for helping those of us with Windows environments stay caught up! i've come across a lot of PECL extensions that haven't gotten new DLLs in a long time.

**Comment by macintoshplus** [comment]
Hi @Hackwar,

The DLLs for for the version 1.1.1 is available here : https://phpext.phptools.online/extension/php/ast-253

**Comment by macintoshplus** [comment]
> @wo80Merci d'aider ceux d'entre nous avec les environnements Windows à rester pris! j'ai rencontré beaucoup d'extensions PECL qui n'ont pas eu de nouvelles DLL depuis longtemps.


Many DLLs are available on this website: https://phpext.phptools.online

If an extension is not built, you can request a build.

**Comment by TysonAndre** [comment]
> The readme.md says to get it from https://windows.php.net/downloads/pecl/releases/ast/ , but there is no current version.
> Who can do something about it?

That apparently changed to https://downloads.php.net/~windows/pecl/releases/ast/ (different domain due to changes in build infrastructure)

https://pecl.php.net/package/ast
