### ISSUE TITLE
Incorrect values for magic constants

### ISSUE THREAD

**Issue by Lerchensporn** [nikic/php-ast#239]
When working on a new [static code analyzer](https://codeberg.org/Lerchensporn/php_static_type_checker) based on this extension I noticed a mismatch between the flags for the magic constants.

Test code:
```
<?php
$ast = ast\parse_code('<?php  __LINE__; __FILE__; __DIR__;', 100);
var_dump($ast, ast\flags\MAGIC_LINE, ast\flags\MAGIC_FILE, ast\flags\MAGIC_DIR);
```

Output:
```
array(3) {
  [0]=>
  object(ast\Node)#2 (4) {
    ["kind"]=>
    int(0)
    ["flags"]=>
    int(343)
    ["lineno"]=>
    int(1)
    ["children"]=>
    array(0) {
    }
  }
  [1]=>
  object(ast\Node)#3 (4) {
    ["kind"]=>
    int(0)
    ["flags"]=>
    int(344)
    ["lineno"]=>
    int(1)
    ["children"]=>
    array(0) {
    }
  }
  [2]=>
  object(ast\Node)#4 (4) {
    ["kind"]=>
    int(0)
    ["flags"]=>
    int(345)
    ["lineno"]=>
    int(1)
    ["children"]=>
    array(0) {
    }
  }
}
int(379)
int(380)
int(381)

```

In the output, the numbers 343, 344, 345 don't match 379, 380, 381. Is this expected?

**Comment by nikic** [comment]
I can't reproduce this, for me the values match. Which PHP version are you using?

**Comment by Lerchensporn** [comment]
PHP 8.3.8 (cli) (built: Jun  7 2024 19:46:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies

**Comment by nikic** [comment]
Here's what I get on PHP 8.3.10:
```
object(ast\Node)#1 (4) {
  ["kind"]=>
  int(132)
  ["flags"]=>
  int(0)
  ["lineno"]=>
  int(1)
  ["children"]=>
  array(3) {
    [0]=>
    object(ast\Node)#2 (4) {
      ["kind"]=>
      int(0)
      ["flags"]=>
      int(343)
      ["lineno"]=>
      int(1)
      ["children"]=>
      array(0) {
      }
    }
    [1]=>
    object(ast\Node)#3 (4) {
      ["kind"]=>
      int(0)
      ["flags"]=>
      int(344)
      ["lineno"]=>
      int(1)
      ["children"]=>
      array(0) {
      }
    }
    [2]=>
    object(ast\Node)#4 (4) {
      ["kind"]=>
      int(0)
      ["flags"]=>
      int(345)
      ["lineno"]=>
      int(1)
      ["children"]=>
      array(0) {
      }
    }
  }
}
int(343)
int(344)
int(345)
```

**Comment by nikic** [comment]
Looking at your values, it seems like you are getting the values from https://github.com/nikic/php-ast/blob/master/ast_stub.php rather than the ones from the extension?

**Comment by Lerchensporn** [comment]
I found the problem. During compilation of the php-ast extension the header files from `/usr/include/php7` were taken, which define different values for constants like T_FILE etc. than PHP 8. After uninstalling the old PHP version and rebuilding the extension, the numbers match.

**Comment by Daimona** [comment]
After some more experiments, this _seems_ to be related to the php8.3-cli package from sury, but I'm not sure how to ultimately prove that.

Using `docker run -it --user root --rm --entrypoint /bin/bash docker-registry.wikimedia.org/releng/sury-php:0.5.1`:
- Building PHP 8.3.21 from source, then building php-ast from source, everything is OK.
- Installing php8.3-cli from sury, then building php-ast from source, has the wrong value for MAGIC_* constants

Interestingly, when I built PHP from source and then installed php8.3-cli in the same container, php8.3-cli also worked correctly.
