### ISSUE TITLE
[ Feature Request ] Add Support for Merging Multiple PHP Files into a Single AST

### ISSUE THREAD

**Issue by NEX-S** [nikic/php-ast#245]
### **Description**
When developing a static PHP code auditing tool, I encountered a limitation with the `php-ast` extension: it does not support merging and parsing multiple related PHP files into a single Abstract Syntax Tree (AST). This restriction hampers the ability to perform cross-file variable taint tracking, which is essential for comprehensive security analysis.

### **Detailed Example**

Consider the following two PHP files:

**file1.php**
```php
<?php
echo "file1.php";
include "file2.php";
?>
```

**file2.php**
```php
<?php
echo "file2.php";
?>
```

Using `php-ast` to parse these files individually results in two separate ASTs. The `include` statement in `file1.php` indicates a dependency on `file2.php`, but `php-ast` does not provide a mechanism to merge these ASTs into a unified structure. This separation makes it challenging to trace variables and perform taint analysis across the included files.

### **Expected Features**

I propose the addition of the following functionalities to the `php-ast` extension:

1. **Combined Parsing Capability**: Introduce a feature that allows users to specify multiple PHP files, which `php-ast` will parse and merge into a single AST. This unified AST should accurately represent the relationships between the files, such as `include`, `require`, `include_once`, and `require_once` statements.

2. **Dependency Resolution**: Automatically detect and resolve file dependencies based on inclusion statements. When an `include` or `require` statement is encountered, the parser should locate the referenced file, parse its AST, and integrate it into the main AST seamlessly.

3. **Configurable Parsing Options**: Provide options to control the parsing behavior, such as:
   - **Automatic Inclusion Parsing**: Enable or disable automatic parsing of included files.
   - **Namespace Handling**: Manage namespaces to prevent naming conflicts when merging ASTs from different files.
   - **Error Handling**: Gracefully handle missing or circular includes without crashing the parser.

4. **Cross-File Analysis Support**: Ensure that the merged AST retains enough contextual information to facilitate advanced static analysis techniques, such as cross-file variable taint tracking, function call analysis, and dependency mapping.

### **Use Cases**

Implementing the proposed features would significantly enhance the capabilities of static analysis tools by enabling:

- **Comprehensive Security Audits**: Perform thorough taint analysis across multiple files to identify vulnerabilities like SQL injection, cross-site scripting (XSS), and other security flaws that span across different parts of an application.

- **Code Dependency Analysis**: Map out dependencies between various PHP files, aiding in refactoring efforts and understanding complex codebases.

- **Enhanced Code Quality Checks**: Conduct more accurate and holistic code quality assessments by analyzing how different files interact and depend on each other.

### **Additional Information**

Currently, `php-ast` excels at parsing individual PHP files into their respective ASTs. However, the lack of support for merging multiple ASTs limits its utility in scenarios where understanding the interplay between different files is crucial. Manually merging ASTs is not only time-consuming but also error-prone, especially when dealing with complex inclusion hierarchies and namespaces.

### **Proposed Solution**

1. **API Extension**: Introduce a new Node that contains the external file / module's ast.

2. **Include Statement Handling**: Enhance the parser to recognize and process inclusion statements (`include`, `require`, etc.) automatically, fetching and integrating the ASTs of the included files into the main AST.

3. **Namespace Management**: Implement mechanisms to handle namespaces effectively during the merging process to avoid naming collisions and maintain code integrity.

4. **Configuration Parameters**: Allow users to customize the merging behavior through additional parameters or configuration settings, enabling flexibility based on different project requirements.

### **Conclusion**

Adding support for merging multiple PHP files into a single AST within the `php-ast` extension would greatly enhance its applicability in advanced static analysis and code auditing tools. This feature is vital for enabling cross-file analyses, such as variable taint tracking, which are essential for identifying security vulnerabilities and ensuring code quality in complex PHP applications.

I hope the maintainers and contributors of `php-ast` will consider this feature request to improve the extension's functionality and support the broader PHP developer community in building more robust and secure applications.

### **Thank You**

Thank you for maintaining the `php-ast` extension and for your continuous efforts to enhance its capabilities. I look forward to your feedback and the potential implementation of this feature to aid in the development of more advanced static analysis tools.

**Comment by nikic** [comment]
This is out of scope for this project, which just provides the AST. It's the responsibility of higher-level static analysis libraries to deal with cross-file analysis, type inference, etc.

For a static analyzer based on php-ast, see https://github.com/phan/phan. For ones based on PHP-Parser, see https://github.com/phpstan/phpstan and https://github.com/vimeo/psalm.
