### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by christopherowen** [nikic/php-ast#25]
Please create a stable release of php-ast in order to meet the distribution rules of the IUS (rhel/centos) repo program, to ease installation on machines that use their compilation of php7.

**Comment by remicollet** [comment]
User of PHP 7 on RHEL / CentOS can use remi repository which provides nearly all available extensions, including ast.

**Comment by oerdnj** [comment]
However I would welcome at least a beta PECL-style release with `package.xml`, so I can apply my default template when packaging ast.

**Comment by pinepain** [comment]
@nikic can you please tag current version so that we can depend on it, not commit hash in php71-ast homebrew formula in this PR - https://github.com/Homebrew/homebrew-php/pull/3408?

**Comment by nikic** [comment]
New tag done: https://github.com/nikic/php-ast/releases/tag/v0.1.2

Should now properly support 7.1

**Comment by pinepain** [comment]
Thanks!

**Comment by carlwgeorge** [comment]
Is this extension still considered "experimental", as the README states?

**Comment by nikic** [comment]
Note dropped in https://github.com/nikic/php-ast/commit/ac993fd50d55cb16158b84cf820f53de57bdf9e0. It's not exactly experimental anymore and the note about non-final AST structure is no longer relevant (as the AST is versioned).

**Comment by nikic** [comment]
A PECL release is now available: https://pecl.php.net/package/ast Thanks to @TysonAndre for setting up the package.xml.

First time I'm doing this, please report if there are any issues.
