### ISSUE TITLE
inconsistent dll linkage

### ISSUE THREAD

**Issue by Jan-E** [nikic/php-ast#26]
Hi @nikic

Your extension and the astkit extension of @sgolemon throw an 'inconsistent dll linkage' error when including zend_language_scanner.h. See https://github.com/sgolemon/astkit/pull/2#issuecomment-216146885

I am not familiar with the zend api, but there seems to be a missing ZEND_API at this line in PHP master:
https://github.com/php/php-src/blob/master/Zend/zend_language_scanner.h#L66

Would it break anything to add it there?

**Comment by nikic** [comment]
As the message says, we're specifying inconsistent linkage in http://lxr.php.net/xref/PHP_MASTER/Zend/zend_stream.h#81 and http://lxr.php.net/xref/PHP_MASTER/Zend/zend_language_scanner.h#66. We should either add ZEND_API to zend_language_scanner.h or, what may be better here, drop it from the zend_language_scanner.h header altogether -- not sure what it's doing there in the first place.

**Comment by Jan-E** [comment]
Will you be the initiator of a fix? Or should I file a bug report?

**Comment by nikic** [comment]
Dropped the declaration from PHP-7.0 and master: https://github.com/php/php-src/commit/d5a38280befda7626c2566a9a3461eebd37a5c17

**Comment by Jan-E** [comment]
Thx
