### ISSUE TITLE
Installation on Ubuntu 16.04 in wrong place

### ISSUE THREAD

**Issue by adamculp** [nikic/php-ast#27]
Using apt-get to install the php-ast package results in the .ini file being created at /etc/php/mods-available/ast.ini instead of /etc/php/7.0/mods-available/ast.ini like the rest of the php extensions.

This required me to copy the ast.ini file to the correct place in order to 'sudo phpenmod ast'. Then all worked as expected.

**Comment by nikic** [comment]
This is some kind of issue with the downstream packaging, which I'm not familiar with. Maybe @oerdnj can help, as Ubuntu probably adopted his package?

**Comment by oerdnj** [comment]
You should report this bug with Ubuntu and not with upstream. @nikic, you can close the bug here.

JFTR it might just need a rebuild with newer `dh_php` if I recall correctly.

**Comment by nikic** [comment]
Okay, closing here.

**Comment by adamculp** [comment]
So, are one of you going to submit this with Ubuntu. Asking so effort and tickets are not duplicated. I also would hate for this to get lost. I'm sure I will not be the only person to notice it.
