### ISSUE TITLE
Flags Documentation?

### ISSUE THREAD

**Issue by Iazel** [nikic/php-ast#35]
Hello! 
I'm quite new to PHP internals and was wondering: where could I find an explanation for flags?

For example, I can't really deduce what `NAME_FQ` and `NAME_NON_FQ` means ^^"

**Comment by nikic** [comment]
FQ is short for "fully qualified". NAME_FQ is a fully qualified name (`\Foo\Bar`), NAME_NOT_FQ is an unqualified (`Foo`) or qualified name (`Foo\Bar`) and NAME_RELATIVE is a relative name (`namespace\Foo`).
