### ISSUE TITLE
Clarifying meaning of "prior to version XX"

### ISSUE THREAD

**Issue by mnapoli** [nikic/php-ast#38]
Hi,

Just to be sure I'm not misunderstanding the README, in https://github.com/nikic/php-ast#ast-node-kinds when I read:

```
AST_AND:              left, right            // prior to version 20
```

That means that `AST_AND` has been removed in v30 and later, and is no longer used?

**Comment by nikic** [comment]
Correct. As of version 20 it is represented as an `AST_BINARY_OP` with `flags\BINARY_BOOL_AND`.

**Comment by mnapoli** [comment]
Thanks!
