### ISSUE TITLE
php 7.1 : php-ast has no constant value to indicate some nullable **internal** types

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#40]
Using the latest version of the master branch, and php 7.1.0

(Applies to ast version 35 and 40)

```
echo ast_dump(ast\parse_code('<?php function foo(?callable $a, ?array $b, ?string $c){}', 35));    
AST_STMT_LIST
    0: AST_FUNC_DECL
        flags: 0
        name: foo
        params: AST_PARAM_LIST
            0: AST_PARAM
                flags: 0
                type: AST_TYPE
                    flags: 270
                name: "a"
                default: null
            1: AST_PARAM
                flags: 0
                type: AST_TYPE
                    flags: 263
                name: "b"
                default: null
            2: AST_PARAM
                flags: 0
                type: AST_NULLABLE_TYPE
                    type: AST_NAME
                        flags: NAME_NOT_FQ (1)
                        name: "string"
                name: "c"
                default: null
        uses: null
        stmts: AST_STMT_LIST
        returnType: null
```

Observed behavior:

- util.php does not dump a list of bitwised ored constant names, it dumps integers (263 = 256|7, 270 = 256|14)
- There doesn't seem to be a constant in util.php for the bit flag 256?
- some types, such as "string", are wrapped in AST_NULLABLE_TYPE. Others aren't (array, callable). Is this so that the output reflects the internal data structure?

Expected behavior:

php-ast extension should either
- expose some constant for 256 (flags\AST_TYPE_BITFLAG_NULLABLE or something, or even AST_TYPE_CALLABLE_NULLABLE)
- Wrap the AST_TYPE for array, callable, etc., in an AST_NULLABLE_TYPE, for consistency

util.php should decode and print the above example in a human readable way.

**Comment by nikic** [comment]
It's supposed to wrap in NULLABLE_TYPE... but handling for this is currently missing for array/callable.

**Comment by nikic** [comment]
Fixed by https://github.com/nikic/php-ast/commit/b815e10fed3bea70d1ace33ff7bbec5ceba874b6.
