### ISSUE TITLE
Windows built for version 40

### ISSUE THREAD

**Issue by jansor** [nikic/php-ast#42]
Hi, i was checking the latest release but cannot see the windows binaries under PECL snapshots.
Where can i download the latest version for windows?

**Comment by nikic** [comment]
@weltling Can you please kick off a new php-ast build (from master or https://github.com/nikic/php-ast/releases/tag/v0.1.4)?

**Comment by weltling** [comment]
Sure, here you are http://windows.php.net/downloads/pecl/snaps/ast/20170126/ :)

Thanks.

**Comment by nikic** [comment]
Thanks!
