### ISSUE TITLE
Split ast-stubs.php into two files for php 7.0 and php 7.1?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#44]
1. It makes it easier to know what types to expect for a php minor version when using this module: e.g. TYPE_ITERABLE doesn't exist in php 7.0
2. The values are going to be different, which will confuse people using the stub file to try to understand serialization(json_encode, var_export, etc.) of a node (Not sure if AST is stable in patch versions)
    \ast\AST_USE is 143 in php 7.1, but is 144 in php 7.0

**Comment by nikic** [comment]
TYPE_ITERABLE does exist in 7.0 -- the extension provides forward-compatiblity defines for all flags and nodes.

In any case, I have no interest in splitting the stubs. The stubs are there for IDE autocompletion only. If you want to inspect the AST, please use the provided dumping function.
