### ISSUE TITLE
Proposal: Move PHP utilities for working with php-ast(util.php) into a namespaced composer package?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#45]
E.g. v0.1.4 could be capable of printing debug output for the stable ast version (40) from v0.1.4 of ext-ast, etc.

Any future changes (e.g. best effort at converting an \ast\node back into valid PHP code, optionally with those line numbers) could be added to those utilities.

**Comment by nikic** [comment]
Sounds reasonable, also requested in #29. There should be no problem with reusing this repo for the composer package, right? I don't fancy doing version synchronization across two repos.

**Comment by TysonAndre** [comment]
Reusing the repo should be fine, feel free to close this as a duplicate
