### ISSUE TITLE
Add internal factory functions to make ast Nodes and Decls?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#47]
Not sure about the order, but something like the below (No validation of $kind, $flags, etc. is expected beyond the type).
Would this be something you would be interested in adding to php-ast if there was a PR for it?

`\ast\make_node(int $kind, int $flags = 0, int lineno = 0, array $children = null) : \ast\Node`
`\ast\make_decl(int $kind, int $flags = 0, int lineno = 0, array $children = null, string $name = null, int endLineno = 0, string $docComment = null) : \ast\Node\Decl`

- If a program constructs a large number of AST nodes, then having functionality to construct ast nodes in C would likely be faster than constructing an object and setting multiple properties from PHP
  (e.g. converting from php-parser to php-ast, or rewriting AST nodes according to a rule, to make them easier to analyze)
- Changing the constructor may cause BC issues, so factories were suggested instead

**Comment by nikic** [comment]
Sounds good to me. Two points:

 * I feel like having those as ctors would be more natural. You mentioned that this would be a BC problem -- can we avoid this by making the `$kind` parameter optional as well?
 * It might be better to use a different argument order, in particular one where `$lineno` is the last argument, for two reasons: a) If you're creating new nodes you quite often don't care about location information and b) it's not unlikely that all AST nodes will have an `$endLineno` at some point. It will be easier to incorporate this if lineno is the last argument.
