### ISSUE TITLE
which one is better?php-ast or php parser

### ISSUE THREAD

**Issue by Rivendall** [nikic/php-ast#48]
Hello 
which one is better?php-ast or php parser
Thank you.

**Comment by nikic** [comment]
There is a detailed discussion of the differences between php-ast and PHP-Parser in the readme: https://github.com/nikic/php-ast#differences-to-php-parser

The tl;dr is that for most purposes PHP-Parser is better. php-ast has exactly one advantage: Better performance. If that's not your top priority, you're likely better of with PHP-Parser.
