### ISSUE TITLE
what is php version? 

### ISSUE THREAD

**Issue by Rivendall** [nikic/php-ast#49]
Hello 
what is php version for php ast? Am I run php ast for php 5.4 of after or befor ? 
Or is it for special version of php? 
and dose create ast for any version of php? 

Thank you.

**Comment by nikic** [comment]
php-ast exposes the internal PHP AST, which is only available as of PHP 7. The extension is only compatible with PHP 7.0 and 7.1. It can also only create an AST for the version you're running on.
