### ISSUE TITLE
Convert AST_CONST_ELEM and AST_PROP_ELEM to \ast\Node\Decl in version 45?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#52]
1. They have a name (as `$node->children['name']`, currently)
2. They have the property docComment set (not part of most of `\ast\Node`, but set as a dynamic property)
3. It may be useful to know the end line number as well, for certain applications (e.g. reporting the start and end line numbers for an issue detected for a property declaration)
4. ReflectionProperty exists.

**Comment by nikic** [comment]
We currently don't have end linenos for these -- that would require migrating to decl node types for these upstream.

I think it might also be worth considering going the other way around and drop the special `Decl` nodes. Apart from the end lineno, the name and docComment can just be normal children. The fact that we have `Decl` nodes right now is an artifact of the internal implementation, and I'm not sure how much sense it really makes.

**Comment by nikic** [comment]
Before proceeding on #55 I'd like to have some feedback on the previous comment. What do you think about dropping Decl nodes and just using one structure for everything? The node/decl distinction is an artifact of the implementation, I don't think keeping the distinction makes much sense.

**Comment by TysonAndre** [comment]
>  What do you think about dropping Decl nodes and just using one structure for everything? 

I think it makes sense. One would want want to keep Decl around for a few releases though, and only unify Nodes in version 45.

**Comment by nikic** [comment]
> I think it makes sense. One would want want to keep Decl around for a few releases though, and only unify Nodes in version 45.

Of course, it will stay around until all current versions of the AST are phased out.

Are there other changes that should go into the next AST version?

**Comment by TysonAndre** [comment]
https://github.com/nikic/php-ast/issues/58 is something I'd want in the next AST version, but not strictly necessary.

Other than that, I can't really think of any enhancements/consistency changes I want.

**Comment by nikic** [comment]
Normalization away from Decl implemented in https://github.com/nikic/php-ast/commit/cca3151415314f97af2116706773dfc9d5f398ba.
