### ISSUE TITLE
For inline HTML, AST_ECHO has a lineno of the end line, not the starting line

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#53]
Not familiar enough with internals to know if this is fixable. Low priority. Tested in php 7.1.2

```
var_export(\ast\parse_code("Hello\nworld\nthirdline", 40))
```

Observed: lineno => 3.
Expected: lineno => 1.

```
'kind' => 282,
'lineno' => 3
```

**Comment by nikic** [comment]
Fixed upstream by https://github.com/php/php-src/commit/f5951cc81bb777e39dbfffb4db1c265f4e51308f.
