### ISSUE TITLE
Tes failure with PHP 7.1.4RC1

### ISSUE THREAD

**Issue by remicollet** [nikic/php-ast#54]
FYI, detected by Fedora QA
https://apps.fedoraproject.org/koschei/package/php-ast?collection=f27

Seems only related to line number

Can you please have a look, so we can try to avoid BC break in upcoming 7.1.4.

**Comment by nikic** [comment]
This is due to an upstream fix in line number assignment. The php-ast test has already been fixed by https://github.com/nikic/php-ast/commit/0aa5b47574a6c4e6a034bfdb41a91f4a0699fb9d, but this is not yet part of a new release.

**Comment by remicollet** [comment]
Thanks

(btw, sorry for the noise, but just wanted to report ASAP various breakage to all affected projects... and thus don't took time to dig in history)

**Comment by nikic** [comment]
Relevant test fix now released, so closing this.
