### ISSUE TITLE
Request: Add an identifier which can be used to uniquely identify a parsed closure (e.g. in combination with line)

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#58]
What is being requested:

- In version 45, add an identifier that can be used to identify a closure returned by `parse_code`, which will be reproduceable if `parse_code` is called multiple times on the same PHP code

Why?

- Creating this identifier from PHP is possible, but would be much slower than doing it from C (A very small fraction of \ast\Nodes are closures)
- Some use cases would normally only need to process part of the tree from PHP, or process the tree in different orders
- Helps with issues such as https://github.com/etsy/phan/issues/767 . if two closures **in the same file** on the same line have the same function types and return types, it's hard to differentiate them
  In one phase, many files are sequentially parsed, processed, and then asts are derefenced to save memory. In the second phase, asts are parsed again to analyze.

Suggested ways of doing that

- The column number (or byte offset from the start of the file), if future versions of the Zend support it (The combination of line number and starting column number would be unique)
- An incrementing counter(globally unique), which is reset to 0 whenever \ast\parse_code is called.
  , e.g. The combination of $closureNode->lineno and $closureNode->children['__closure_identifier']

**Comment by nikic** [comment]
We actually store a lexer pointer on declaration nodes for pretty much that purpose. For this extension we could expose it as an offset. However, IIRC this is not going to be the actual start position of the closure, but basically some arbitrary (but unique) point in it (e.g. after the function keyword, would have to check).

**Comment by nikic** [comment]
Just checked, the lex_pos points past the end of the function declaration, so directly exposing that offset is probably not the best idea.
