### ISSUE TITLE
What's the status of ZEND_ACC_GENERATOR for functions in php 7.1

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#64]
The flags for AST_FUNCTION (etc?) seem to include ZEND_ACC_GENERATOR in php 7.1 (but not php 7.0, I assume due to a limitation or design change)

Right now, util.php just dumps it as an undocumented constant.

It would be convenient to know what to expect for this bit value, to have util.php dump this bit value, and whether the flag can be relied on to be there in future php patch releases.

php 7.0

```php
php > var_dump( \ast\parse_code('<?php function foo(){yield;}', 40));
object(ast\Node)#1 (4) {
  ["kind"]=>
  int(133)
  ["flags"]=>
  int(0)
  ["lineno"]=>
  int(1)
  ["children"]=>
  array(1) {
    [0]=>
    object(ast\Node\Decl)#2 (7) {
      ["kind"]=>
      int(66)
      ["flags"]=>
      int(0)
...
```

php 7.1:

```php
object(ast\Node)#1 (4) {
  ["kind"]=>
  int(132)
  ["flags"]=>
  int(0)
  ["lineno"]=>
  int(1)
  ["children"]=>
  array(1) {
    [0]=>
    object(ast\Node\Decl)#2 (7) {
      ["kind"]=>
      int(66)
      ["flags"]=>
      int(8388608)
```

**Comment by nikic** [comment]
Generator creation underwent some changes in 7.1, as part of which detection of generators has been moved from compilation to parsing. I think it's safe to assume that this flag will continue to exist, so yeah, this flag should be exported as a constant and added to utils/readme.

**Comment by nikic** [comment]
Flag constant added in https://github.com/nikic/php-ast/commit/4d680f5554220f7b2b0a7f29979c4b094e25ac86.
