### ISSUE TITLE
Specify versions in a way that composer can depend on version ranges

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#71]
Currently, versions get removed from 0.1.x, so a composer dependency on ~0.1.5 may break in a future unknown release (e.g. 0.1.8)

Changing version numbers would make it easier to specify version ranges for packages such as phan, etc, and to allow simultaneous installations of packages using php-ast

Proposed

- bump minor version when an old ast version is removed
- bump major version if a PHP version (e.g. 7.0) stops being supported

**Comment by nikic** [comment]
Good point. I will bump the minor when removing version in the future.
