### ISSUE TITLE
Running the tests on Appveyor/Windows

### ISSUE THREAD

**Issue by Jan-E** [nikic/php-ast#72]
@nikic Did you ever consider to run the tests on Windows as well? It is fairly easy.

See https://github.com/Jan-E/php-ast/pull/1 with these results:
https://ci.appveyor.com/project/Jan-E/php-ast/build/master.2

**Comment by nikic** [comment]
I've just added this repo on AppVeyor. Would you mind submitting your PR against it?

**Comment by Jan-E** [comment]
Done: https://ci.appveyor.com/project/nikic/php-ast/build/master.1

**Comment by Jan-E** [comment]
And the PR, of course: https://github.com/nikic/php-ast/pull/73
