### ISSUE TITLE
Windows binaries seem not to define the ast\get_metadata() function

### ISSUE THREAD

**Issue by fracz** [nikic/php-ast#74]
I have installed the extension with a prebuilt Windows binaries and the example code with `$var = 42` works great.

However, when I try to parse something more complicated, it ends up with the following error:

> Call to undefined function ast\get_metadata() in util.php on line 13

I have noticed that this function [has been added recently](https://github.com/nikic/php-ast/issues/62#issuecomment-318856233). Could you check if the [prebuild binaries](http://windows.php.net/downloads/pecl/releases/ast/0.1.5/) include it properly, please?

**Comment by nikic** [comment]
The get_metadata() function is not yet part of a release and as such also not in the pre-built binaries. For now I would suggest to use the util.php file that corresponds to the 0.1.5 release: https://github.com/nikic/php-ast/blob/v0.1.5/util.php
