### ISSUE TITLE
Publish latest release on PECL and Launchpad

### ISSUE THREAD

**Issue by mridang** [nikic/php-ast#75]
The version on PECL is rather stale: http://pecl.php.net/package/Ast Maybe publishing the latest build on Launchpad would be helpful as well: https://packages.ubuntu.com/xenial/php/php-ast

**Comment by TysonAndre** [comment]
0.1.5 is the latest release. See https://github.com/nikic/php-ast/releases

Also, the Ubuntu  (and other OS package managers) packagers have their own issue tracker for requesting updates

**Comment by TysonAndre** [comment]
Although launchpad is unrelated to the github project, if launchpad were to upgrade to 0.1.5 directly, anything that happened to use `extension=php-ast` would break.
What is using it, anyway? I don't see an easy upgrade path. (`apt-get upgrade` may break applications)

https://github.com/nikic/php-ast/tree/v0.1.1 says that AST version 30 is experimental (i.e. the bleeding edge, and may change slightly)
https://github.com/nikic/php-ast/tree/v0.1.5 says that AST version 30 is deprecated (e.g. would emit E_DEPRECATED depending on other php.ini settings.

**Comment by nikic** [comment]
I plan to release a new version with get_metadata() and get_supported_versions() soon. Anything else I should do before that?

**Comment by TysonAndre** [comment]
I can't think of anything else.

**Comment by nikic** [comment]
I've released a new version on PECL, so closing this issue.
