### ISSUE TITLE
Add internal function function ast\get_supported_versions() to return the list of supported versions?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#77]
Proposed API

```php
namespace ast;
/** @return int[] versions in ascending order */
function get_supported_versions(bool $exclude_deprecated = false) : array {
     return $exclude_deprecated ? [40, 45, 50] : [30, 35, 40, 45, 50];
}
```

I don't think there's a convenient way to get this information right now, apart from parsing the message of the LogicException

- E.g. if attempting to run unit tests for multiple AST versions, or using version 55 if it's available in a dev build

**Comment by nikic** [comment]
Sounds good to me
