### ISSUE TITLE
Mention workarounds for platform dependence limitations of php-ast

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#81]
From the README:

> php-ast may only parse code that is syntactically valid on the version of PHP it runs on. This means that it's not possible to parse code using features of newer versions (e.g. PHP 7.1 code while running on PHP 7.0). Similarly, it is not possible to parse code that is no longer syntactically valid on the used version (e.g. some PHP 5 code may no longer be parsed -- however most code will work). PHP-Parser supports parsing both newer and older (up to PHP 5.2) versions.

https://github.com/tysonandre/php-parser-to-php-ast and https://github.com/tysonandre/tolerant-php-parser-to-php-ast are two projects I am working on that could be used to work around that limitation.

I was thinking about creating composer packages that would create substitute `ast\parse_code()` implementations that depended on the previous two packages (Throw ParseError like default).
Thoughts?

Not being able to tolerate syntax errors is also a limitation of php-ast compared to php-parser (and tolerant-php-parser) that isn't mentioned.

- Another goal (not complete yet) of \*-to-php-ast is: When given syntactically invalid PHP code, generate `ast\Node` trees that would be equivalent to the tree for some other syntactically valid PHP code (by substituting or eliminating nodes)

> php-ast only runs on PHP >= 7.0, as prior versions did not use an internal AST. PHP-Parser supports PHP >= 5.4.

Not in a user-friendly state right now, but I had some success using https://github.com/TysonAndre/Transphpile (converting php 7.1 code to 5.6 code) in order to run php-parser-to-php-ast on php 5.6 in a project (Outdated). See https://github.com/TysonAndre/phan/pull/83/files#diff-44bad6d07b93179f2ae795ab1d6819b1

**Comment by nikic** [comment]
I've added a note in the readme in https://github.com/nikic/php-ast/commit/1b2d5186745911eeffc6c0b24c751921810a6bdf, which can be expanded further.
