### ISSUE TITLE
Is it possible to return the line which $node->docComment starts on?

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#84]
(In other words, the line where `/**` is.)

Is this information available right now in the C AST parsing library used by this extension?
If so, $node->children['docCommentStartLine'] or $node->docCommentStartLine may be useful 

https://github.com/phan/phan/issues/1294 (Calculating line for `@param`) is an example use case.

**Comment by nikic** [comment]
Nope, unfortunately we don't have this information.
