### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by XedinUnknown** [nikic/php-ast#95]
Hi,

I've followed the instructions:

1. I am running PHP 7.1.12 on Windows 10.
2. I downloaded the files from [here](https://windows.php.net/downloads/pecl/releases/ast/0.1.6/php_ast-0.1.6-7.0-nts-vc14-x64.zip).
3. I placed the `php_ast.dll` into the respective `ext` folder.
4. I added `extension=php_ast.dll` to my `php.ini`

Now when I run `php -v`, I get the following output:

```
C:\php>php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\7.1.12\ext\php_ast.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\php\7.1.12\ext\php_ast.dll' - The specified module could not be found.
 in Unknown on line 0
PHP 7.1.12 (cli) (built: Nov 23 2017 04:21:28) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

This can result from the file not being found, but I'm sure it's there. It can also result in the extension's dependency not being found, but there are no dependencies specified.

Could someone kindly advise?

**Comment by TysonAndre** [comment]
The URL you linked was https://windows.php.net/downloads/pecl/releases/ast/0.1.6/php_ast-0.1.6-7.0-nts-vc14-x64.zip

That's the module for PHP 7.0. You need to download the module for PHP 7.1. and you need to use ZTS (same as PHP --version), not NTS

**Comment by XedinUnknown** [comment]
This works, thank you. Apparently, I hadn't noticed that the filename contains the PHP version as well, confusing it with some patch version, and following only the VC version.
